dist: xenial
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install pytest==3.8.0 pytest-cov==2.6.0 codecov flake8

script:
  - pytest --cov=torapp
  - flake8

after_success:
  - codecov
